### ISSUE TITLE
Upload to the central Maven repository

### ISSUE THREAD

**Issue by joelhegg** [tfoxcroft/recurly_integration#1]
Terence, this project is just what I was looking for. Were you the original author? If so, would you mind making it available in the central Maven repository? https://maven.apache.org/guides/mini/guide-central-repository-upload.html

Thanks,
Joel

**Comment by tfoxcroft** [comment]
Hi Joel,

I'm glad you found this useful, I developed it as part of a project I'm working on and will be looking to expand on it in the coming months. That's a great suggestion, I'd be more than happy to upload it to the central Maven repository (thanks for the link). I don't have time immediately, but will look to have this done by 5th of August.

Regards,
Terence
